data:
    root: datasets/VinDr-mammo
    dataset_name: VinDr
    batch_size: 32
    workers: 4
    task: density  
    laterality: all  
    analysis: multi

arch:
    num_classes: 4  
    model: resnet50
    pretrained: true
    dropout: 0.2

loss:
    annealing_coef: 0.5

optimizer:
    type: adam
    lr: 0.0001
    lr_decay_epochs: [10, 15]
    momentum: 0.9
    weight_decay: 0.0001

training:
    fusion_type: DL
    logs_dir: logs
    checkpoints_dir: checkpoints
    print_freq: 10
    checkpoint_epochs: 1
    experiment_name: vindr_density_classification
    log_dir: logs/vindr
    epochs: 20
    resume: